[package]
name = "l1-blockchain"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10"
hex = "0.4"
ed25519-dalek = { version = "2", default-features = false, features = ["std", "rand_core"] }

[dev-dependencies]
rand = "0.8"